services:
  - type: web
    name: AttendanceManagement # Renderでのサービス名
    env: php # ★★★ ここで「PHP環境を使う」と明示的に指定 ★★★
    plan: free # 無料プランを指定
    buildCommand: "composer install --optimize-autoloader --no-dev"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_KEY
        generateValue: true # APP_KEYを自動生成
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        fromDatabase:
          name: attendance-db # ↓で作成するデータベースの名前
          property: connectionString # 接続文字列をDATABASE_URLとして提供

databases:
  - name: attendance-db # Render上で作成するデータベースの名前
    databaseName: attendance_db # 実際のDB名
    plan: free # 無料プラン
    # (オプション) MySQLを使いたい場合。デフォルトはPostgreSQL
    # engine: mysql
    # mySQLVersion: 8